import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'

import '../styles/globals.css'

import { Toaster } from 'sonner'

import { cn } from '@/lib/utils'
import { TailwindIndicator } from '@/components/tailwind-indicator'
import { ThemeProvider } from '@/components/theme-provider'

const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin'],
})

const biotif = localFont({
    src: [
        {
            path: '../styles/fonts/Biotif-Regular.woff2',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../styles/fonts/Biotif-RegularItalic.woff2',
            weight: '400',
            style: 'italic',
        },
        {
            path: '../styles/fonts/Biotif-Bold.woff2',
            weight: '700',
            style: 'normal',
        },
    ],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='it-IT'>
            <body className={cn(inter.className, biotif.className)}>
                <ThemeProvider attribute='class' defaultTheme='dark' enableSystem={false}>
                    {children}
                    <Toaster />
                    <TailwindIndicator />
                </ThemeProvider>
            </body>
        </html>
    )
}
